<template>
    <div class="page">
        <section class="intro"><div><p class="eyebrow">NOTES / DIGITAL GARDEN</p><h1>Notes from<br />the orbit.</h1></div><div><p>Short observations, technical notes, architecture decisions, and unfinished thoughts worth keeping around.</p><div class="filters"><span class="active">All notes</span><span>Engineering</span><span>AI</span><span>Build log</span></div></div></section>
        <RouterLink to="/Notes/dynamic-background" class="feature-link"><NeonGlass class="feature" glow interactive><div><p class="eyebrow">FEATURED NOTE</p><h2>Designing a background that changes with time</h2><p>How CSS gradients, Canvas stars, cloud layers, and time-based theme tokens can make a personal site feel alive without turning it into a visual distraction.</p><span class="mono">Sep 2026 · 6 min read</span></div><div class="orbit"><span></span></div><b>Read note ↗</b></NeonGlass></RouterLink>
        <section class="section"><p class="eyebrow">RECENT NOTES</p><h2>Things worth returning to</h2><div class="list"><NeonGlass v-for="item in notes" :key="item.title" class="row" interactive><span class="mono date">{{ item.date }}</span><div><h3>{{ item.title }}</h3><p>{{ item.description }}</p></div><span class="mono tag">{{ item.tag }}</span><b>↗</b></NeonGlass></div></section>
    </div>
</template>
<script setup>
import NeonGlass from "@/components/ui/NeonGlass.vue"
const notes=[
 {date:"2026.09",title:"From cards to a visual system",description:"Turning one NeonGlass component into a repeatable page language.",tag:"DESIGN · SYSTEM"},
 {date:"2026.09",title:"Why the Lab stays unfinished",description:"A small rule for keeping experimental work playful and useful.",tag:"BUILD LOG"},
 {date:"2026.08",title:"Agents should know where data comes from",description:"Notes on SQL-oriented agents, context boundaries, and trust.",tag:"AI · DATA"},
 {date:"2026.08",title:"Modular monolith before microservices",description:"A reminder about boundaries, deployment, and premature complexity.",tag:"ARCHITECTURE"},
]
</script>
<style scoped lang="scss">
.page{width:min(1180px,calc(100% - 40px));margin:56px auto 0}.eyebrow{margin:0;color:var(--color-accent-primary);font-size:10px;letter-spacing:.14em}.intro{display:grid;grid-template-columns:.8fr 1.2fr;gap:70px;align-items:end;min-height:260px}.intro h1{margin:18px 0 0;font-size:clamp(42px,5vw,58px);line-height:1.05;letter-spacing:-.045em}.intro>div:last-child>p{color:var(--color-text-secondary);font-size:16px;line-height:1.7}.filters{display:flex;gap:10px;flex-wrap:wrap;margin-top:28px}.filters span{padding:9px 14px;border:1px solid var(--color-border-glow);border-radius:999px;color:var(--color-text-secondary);background:var(--color-chip-bg);font-size:11px}.filters .active{color:var(--color-accent-primary);border-color:var(--color-accent-primary)}.feature-link{text-decoration:none;color:inherit}.feature{min-height:360px;margin-top:70px;padding:30px;display:grid;grid-template-columns:1fr 220px;gap:40px}.feature>*{position:relative;z-index:1}.feature h2{max-width:760px;margin:24px 0 18px;font-size:38px;line-height:1.12}.feature p:not(.eyebrow){max-width:760px;color:var(--color-text-secondary);line-height:1.7}.feature .mono{display:block;margin-top:34px;color:var(--color-text-secondary);font-size:10px}.feature b{position:absolute;left:30px;bottom:28px}.orbit{display:grid;place-items:center}.orbit::before{content:"";width:170px;height:170px;border:1px solid var(--color-accent-primary);border-radius:50%;opacity:.35}.orbit span{position:absolute;width:42px;height:42px;border-radius:50%;background:var(--color-accent-secondary);box-shadow:0 0 28px color-mix(in srgb,var(--color-accent-secondary) 50%,transparent)}.section{margin-top:84px}.section h2{margin:10px 0 28px;font-size:34px}.list{display:grid;gap:16px}.row{min-height:130px;display:grid;grid-template-columns:100px 1fr auto 28px;gap:22px;align-items:center;padding:22px 24px}.row>*{position:relative;z-index:1}.date,.tag{color:var(--color-text-secondary);font-size:10px}.row h3{margin:0 0 8px;font-size:21px}.row p{margin:0;color:var(--color-text-secondary);font-size:13px}.row b{color:var(--color-accent-primary)}
@media(max-width:800px){.intro{grid-template-columns:1fr}.feature{grid-template-columns:1fr}.orbit{display:none}.row{grid-template-columns:1fr 24px}.date{grid-column:1/-1}.tag{display:none}}
@media(max-width:520px){.filters{flex-wrap:nowrap;overflow-x:auto}.filters span{white-space:nowrap}.feature h2{font-size:30px}}
</style>
