<template>
    <div class="page">
        <section class="intro"><div><p class="eyebrow">LAB / EXPERIMENTAL SPACE</p><h1>A place to break things,<br />learn, and try again.</h1></div><div><p>Games, prototypes, interaction tests, and technical demos live here before they become something more permanent.</p><div class="status mono"><span>● 3 experiments</span><span>○ always unfinished</span></div></div></section>
        <section class="section"><p class="eyebrow">FEATURED EXPERIMENTS</p><h2>Play first. Explain later.</h2><div class="grid"><RouterLink v-for="(item,index) in experiments" :key="item.title" :to="item.path" class="card-link"><NeonGlass class="lab-card" :glow="index===0" interactive><p class="eyebrow">{{ item.type }}</p><h3>{{ item.title }}</h3><p>{{ item.description }}</p><span>Launch ↗</span></NeonGlass></RouterLink></div><NeonGlass class="note"><p class="eyebrow">LAB NOTE</p><h3>Experiments stay intentionally lightweight.</h3><p>The Lab is where ideas can be incomplete. A prototype only needs to answer one question well enough to deserve the next iteration.</p></NeonGlass></section>
        <section class="section"><p class="eyebrow">DEMO CONSOLE</p><h2>Signals moving through the wire</h2><NeonGlass class="console" glow><div class="mono"><span>● socket://connected</span><span>[18:10:08] client → hello RayM Lab</span><span>[18:10:09] server → message received</span><span>[18:10:12] client → ping</span><strong>[18:10:12] server → pong</strong></div><RouterLink to="/Demo/SocketDemo">Try Socket Demo ↗</RouterLink></NeonGlass></section>
    </div>
</template>
<script setup>
import NeonGlass from "@/components/ui/NeonGlass.vue"
const experiments=[
 {type:"GAME / GENERATION",title:"Maze",description:"A compact maze generator and play surface for experimenting with grid logic.",path:"/Game/Maze"},
 {type:"GAME / LOGIC",title:"Sudoku",description:"A classic constraint puzzle used as a playground for state and interaction.",path:"/Game/Sudoku"},
 {type:"DEMO / NETWORK",title:"Socket Demo",description:"A WebSocket sandbox for client/server messaging and connection behavior.",path:"/Demo/SocketDemo"},
]
</script>
<style scoped lang="scss">
.page{width:min(1180px,calc(100% - 40px));margin:56px auto 0}.eyebrow{margin:0;color:var(--color-accent-primary);font-size:10px;letter-spacing:.14em}.intro{display:grid;grid-template-columns:1.1fr .9fr;gap:64px;align-items:end;min-height:260px}.intro h1{margin:18px 0 0;font-size:clamp(42px,5vw,58px);line-height:1.05;letter-spacing:-.045em}.intro>div:last-child>p{color:var(--color-text-secondary);font-size:16px;line-height:1.7}.status{display:flex;gap:12px;margin-top:28px;color:var(--color-text-secondary);font-size:10px}.status span:first-child{color:var(--color-accent-primary)}.section{margin-top:84px}.section h2{margin:10px 0 28px;font-size:34px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.card-link{text-decoration:none;color:inherit}.lab-card{min-height:250px;padding:24px}.lab-card>*{position:relative;z-index:1}.lab-card h3{margin:14px 0;font-size:26px}.lab-card p:not(.eyebrow){color:var(--color-text-secondary);font-size:13px;line-height:1.65}.lab-card span{position:absolute;left:24px;bottom:24px;color:var(--color-text-primary);font-size:13px}.note{margin-top:22px;padding:24px}.note>*{position:relative;z-index:1}.note h3{margin:12px 0;font-size:24px}.note p:last-child{max-width:880px;color:var(--color-text-secondary);line-height:1.65}.console{min-height:300px;padding:26px;display:flex;justify-content:space-between;gap:30px}.console>*{position:relative;z-index:1}.console>div{display:grid;gap:24px;color:var(--color-text-secondary);font-size:12px}.console>div span:first-child,.console strong{color:var(--color-accent-primary);font-weight:400}.console a{align-self:flex-end;color:var(--color-text-primary);text-decoration:none}
@media(max-width:850px){.intro{grid-template-columns:1fr}.grid{grid-template-columns:1fr}.console{flex-direction:column}.section{margin-top:68px}}
</style>
