# 一个简单的 GitHub Pages 部署工作流
name: 自动化部署

on:
  # 这个选项可以使你手动在 Action tab 页面触发工作流
  workflow_dispatch:
  # 仅在推送到默认分支时运行
  push:
    branches: ['master']


# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # 单次部署的工作描述
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出
        uses: actions/checkout@v4
      - name: 设置Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - name: 安装依赖
        run: npm install
      - name: 构建
        run: npm run build
      - name: 设置页面
        uses: actions/configure-pages@v5
      - name: 上传制品
        uses: actions/upload-pages-artifact@v3
        with:
          # 上传 dist 文件夹
          path: './dist'
      - name: 部署至GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
